server:
  port: 8080

spring:
  application:
    name: cloud-intelligence-forum
  datasource:
    # 加上 allowPublicKeyRetrieval=true 和 serverTimezone
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Cz.200406146737
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JSON序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # ⽇期格式
    default-property-inclusion: NON_NULL # 不为null时序列化
# 设置 Mybatis 的 xml 保存路径
mybatis:
  mapper-locations: classpath:mapper/**/*.xml # 指定 xxxMapper.xml的扫描路径
  configuration: # 配置打印 MyBatis 执行的 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #自动驼峰转换
# ⽇志配置
logging:
  level:
    root: info # 默认⽇志级别
    com:
      forum:
        demo: debug
  file:
    name: logs/springboot.log
# OpenAPI文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER #Springfox-Swagger兼容性配置

cloud-intelligence-forum:
  login:
      url: sign-in.html # 未登录状况下强制跳转⻚⾯
  index: # 首页配置节点
    board-num: 9 # 首页中显示的版块个数